### ISSUE TITLE
对于import type类型的引用是否可以忽略

### ISSUE THREAD

**Issue by Kedaxiang** [emosheeep/circular-dependency-scanner#4]
对于这种import type来说，循环引用应该也不会引发代码问题，感觉可以在ast中忽略对import type的获取
![111111](https://github.com/user-attachments/assets/ad6b410f-2d6a-47e5-b490-c25029245b42)

**Comment by emosheeep** [comment]
Try circular-dependency-scanner@2.3.0-beta.0 with `--exclude-types` param.

**Comment by Kedaxiang** [comment]
it looks good to me👍
